### PR TITLE
Revert ledger bug fix

### PR DESCRIPTION
**Pull request by clevinson**
This PR reverts the components of #35 that were workarounds for the bug identified in Regen Ledger by @amaurym (https://github.com/regen-network/regen-ledger/pull/1480).

Yesterday we realized that Registry App does not in fact pass serialized sign bytes to Keplr, but rather the structured `signDoc`. This `signDoc` is used by Keplr for both amino serialization (to fwd to a hardware wallet) as well as for proto serialization (to encode in `TxRaw`).  Because of this, there's no way to only strip out the top level `{'type': 'regen.core.MsgSend', 'value': '...'}` wrapper for amino serialization without forking the Keplr extension itself (something we don't want to do).

#35 still includes important work (all the amino converters are implemented, and have proper handling of default values, with several test cases written for most messages).  This PR reverts the now unnecessary components of #35 that had to do with https://github.com/regen-network/regen-ledger/pull/1480.

**Note:** Amino tests will fail in CI on this PR as there is not yet any dockerized infrastructure to fold the running of `packages/api/e2e/regen-ledger` it into CI.

### CODE REVIEW

**Review by mhagel — APPROVED** [review]

**Comment by clevinson** [comment]
So I've updated this PR to include an update to the tests so that we can now run tests against a locally configured regen node.

To summarize the changes in this PR are:
- remove dependency on our CosmJS fork (this the main fix)
- add new folder `packages/api/e2e/regen-ledger` with bash scripts for starting up a local regen node, and populating it with test data

To the run the tests locally you need to have two terminals.

In the first one:
1. Clone regen-ledger, checkout `v4.1.2` and run `make build`
2. cd into `packages/api/e2e/regen-ledger` and make a copy of `.env.sample` into your own `.env` file
3. Edit .env file to point `REGEN_BIN` to your built binary from (1). This should be in `build` directory within the cloned repo.
4. Run `source .env && ./bootstrap.sh` from within `packages/api/e2e/regen-ledger`
5. This will setup a local single validator network, populate it with some initial ecocredit data required for the amino testing suite, and begin running the node

In the second terminal:
1. Run `yarn test` from within `packages/api` (make sure the tests you want to verify are not being skipped)

**Comment by clevinson** [comment]
I verified that all tests pass using the above steps. IMO we should try and dockerize this flow so that we can have these tests running in CI again. Is that something that @mhagel you or someone else on the interfaces team would feel comfortable taking over from here?

**Review by mhagel — APPROVED** [review]

**Comment by mhagel** [comment]
>I verified that all tests pass using the above steps. IMO we should try and dockerize this flow so that we can have these tests running in CI again. Is that something that @mhagel you or someone else on the interfaces team would feel comfortable taking over from here?

@wgwz Could you assist with this?

**Comment by mhagel** [comment]
confirmed tests pass locally.

**Comment by mhagel** [comment]
New issue to dockerize test flow #59

**Pull request merged**
