### PR TITLE
fix: minimal ts erros for group-ui imports

### PR DESCRIPTION
**Pull request by ryanchristo**
This pull request includes minimal typescript fixes needed for the amino signing support solution in groups-ui:

- https://github.com/regen-network/groups-ui/pull/69

This is only a temporary fix and generating the code will overwrite the changes here but this would unblock us from adding amino signing support to the groups-ui.

### CODE REVIEW

**Comment by ryanchristo** [comment]
This is not the ideal solution but I think we should tag another alpha version with the changes here so that we can at least get the groups ui working with amino support in the meantime while continuing to investigate a solution to #84.

**Review by blushi — APPROVED** [review]
I pulled this locally, then run `yarn build` and then using `yarn link` to use my local version of @regen-network/api in groups-ui `ryan/10-amino-signing-support` but I still get typescript errors in `dev` or `build`...
Maybe I have something wrong in my set up or I've missed a step, I haven't dug too much into it at this point.

Other than that I'm fine with those changes so we can move forward with that, as long as we add a note in the README about that.

**Comment by ryanchristo** [comment]
> Maybe I have something wrong in my set up or I've missed a step, I haven't dug too much into it at this point.

Hmm... I'm not sure. I was importing the local package in `package.json` to test. I haven't used `yarn link` before. I remove the node modules and rebuild with the local import to test. Probably not the most efficient but it does the trick. I just double checked to make sure and `build` and `dev` in groups-ui seems to be working for me.

If you run `yarn build`, you will overwrite the changes here. Maybe that's what happened?

> Other than that I'm fine with those changes so we can move forward with that, as long as we add a note in the README about that, so pre-approving.

Note added https://github.com/regen-network/regen-js/pull/79/commits/28a68b204dba06f32c422dac3e5296044994957c

**Comment by ryanchristo** [comment]
> Maybe I have something wrong in my set up or I've missed a step, I haven't dug too much into it at this point.

It might also have been `strict` mode being set within groups ui (see https://github.com/regen-network/groups-ui/pull/69/commits/29e58c420f52c596f200815a22ad69d6b47adca9).

**Pull request merged**
