### PR TITLE
chore: update telescope

### PR DESCRIPTION
**Pull request by aaronc**

### CODE REVIEW

**Comment by clevinson** [comment]
utACK @aaronc generally looks good. Are there any concerns around breaking changes? I'm not sure how to test or look for that.

If you think that isn't a concern to be worried about, I can mark this as approved and we can get it merged.

**Comment by aaronc** [comment]
The underlying osmonauts dependencies throw runtime errors asking to upgrade so at least for me it's impossible to use this package without this PR. No idea how this is working in our app currently. @blushi can you take a quick look?

**Comment by blushi** [comment]
> The underlying osmonauts dependencies throw runtime errors asking to upgrade so at least for me it's impossible to use this package without this PR. No idea how this is working in our app currently. @blushi can you take a quick look?

Currently our app is not using the latest version of @regen-network/api that's based on telescope but a former one that was just based on ts-proto with a custom implementation. There's quite a bit of work involved to migrate and that hasn't been prioritized.

Telescope-based version of this package is used in groups-ui though. But AFAIK, there were also some issues with amino signing with telescope that @ryanchristo had faced in particular when working with groups-ui (see https://github.com/regen-network/groups-ui/issues/105 and https://github.com/regen-network/regen-js/issues/70). But not sure if it's a concern anymore with latest version.

What do you want to use this for?

**Comment by aaronc** [comment]
> What do you want to use this for?

So I was trying to play around with an idea of a data explorer after chatting with @clevinson about the idea. Basically some sort of really data focused blockchain explorer, that would look at the metadata on credits and try to resolve it with the data module and verify hashes for users.

**Pull request merged**
